### ISSUE TITLE
无法进入网易有钱网页版

### ISSUE THREAD

**Issue by yuebanquan** [Youthink/netease-rich-bill-export#1]
https://qian.163.com/pc/login.html
会自动跳转到网易有钱APP下线公告
https://1.163.com/html/qian/web/5fdaffaed605e84a6d118cd4.html

**Comment by imfycc** [comment]
> https://qian.163.com/pc/login.html
> 会自动跳转到网易有钱APP下线公告
> https://1.163.com/html/qian/web/5fdaffaed605e84a6d118cd4.html

现在又能进去了，上午我这边也是跳转到公告。现在又能进去了。你试试。

**Comment by imfycc** [comment]
我测试了一下：

现在访问 https://qian.163.com 会跳转公告上。

https://qian.163.com/pc/index.html
https://qian.163.com/pc/login.html

可以正常访问
